### ISSUE TITLE
Windows metrics hangs and don't appear in Graphite

### ISSUE THREAD

**Issue by corest** [sensu/sensu-community-plugins#1109]
I'm using those windows metrics checks: [CPU](https://github.com/sensu/sensu-community-plugins/blob/master/plugins/windows/windows-cpu-load-metrics.rb "CPU"), [RAM](https://github.com/sensu/sensu-community-plugins/blob/master/plugins/windows/ram-usage-windows.rb "RAM"), [Disk](https://github.com/sensu/sensu-community-plugins/blob/master/plugins/windows/disk-usage-metrics.rb "Disk")
They all have proper output format for graphite. I created metric check on sensu server and i'm trying to collect metrics from Windows host to graphite. I'm sure that graphite is configured properly, because with linux hosts everything works fine. But with Windows host looks like checks just hang. Here is log:

>{"timestamp":"2015-03-31T11:08:31.276518+0300","level":"info","message":"received check request","check":{"name":"windows_disk_metrics","issued":1427789179,"command":"/etc/sensu/plugins/disk-usage-metrics.rb --scheme stats.:::name:::"}}
{"timestamp":"2015-03-31T11:08:31.276518+0300","level":"warn","message":"previous check command execution in progress","check":{"name":"windows_disk_metrics","issued":1427789179,"command":"/etc/sensu/plugins/disk-usage-metrics.rb --scheme stats.:::name:::"}}

Here is my metric check on server:

>{
  "checks": {
    "windows_ram_metrics": {
      "type": "metric",
      "handlers": ["graphite_load_amqp"], 
      "command": "/etc/sensu/plugins/ram-usage-windows.rb --scheme stats.:::name:::",
      "interval": 60,
          "subscribers": ["WRAM_METRIC"]
    },
    "windows_disk_metrics": {
      "type": "metric",
      "handlers": ["graphite_load_amqp"],
      "command": "/etc/sensu/plugins/disk-usage-metrics.rb --scheme stats.:::name:::",
      "interval": 60,
          "subscribers": ["WDISK_METRIC"]
    },
    "windows_cpu_metrics": {
      "type": "metric",
      "handlers": ["graphite_load_amqp"],
      "command": "/etc/sensu/plugins/windows-cpu-load-metrics.rb --scheme stats.:::name:::",
      "interval": 60,
          "subscribers": ["WCPU_METRIC"]
    }
  }  
}

It is strange. I checked rabbitmq and there is working connection between my Windows host and rabbitmq. And when i restart service on windows - i see data transfer from machine to rabbitmq. But on next run (when metric process is still in execution state) - rabbitmq doesn't receive any data from machine anymore. It can get only one metrics data-set after service restart on Windows host.

**Comment by mattyjones** [comment]
@rmc3

Thoughts

**Comment by rmc3** [comment]
@corest, the logs you provided do suggest that the checks are either not returning, or Sensu is not properly detecting that they're returning.

Looking at the log output, I suspect that the problem is your Windows server is receiving Linux shell-style commands to be executed in the check request, e.g., ```/etc/sensu/plugins/disk-usage-metrics.rb --scheme stats.:::name:::```

There are a couple of problems here:

1. I may be incorrect, but I don't think Windows has a way of finding the path ```/etc/sensu/plugins/disk-usage-metrics.rb```. You'd probably need at least a drive letter on the front of that, like ```C:\```
2. Windows shells don't support shebangs, so it has no way of knowing what interpreter to use to execute that script. As a result, you probably need to call the ruby interpreter with the script as an argument

In my test environment, Ruby is at ```C:\opt\sensu\embedded\bin\ruby.exe``` and my plugin scripts are in ```C:\opt\sensu\etc\sensu\plugins```. So, to run this check in my environment, it'd look like the following:

```
C:\opt\sensu\embedded\bin\ruby.exe C:\opt\sensu\etc\sensu\plugins\disk-usage-metrics.rb --scheme stats.:::name:::
```

You'd probably need to adjust the paths on that to fit your environment.

Note that either forward slashes or back slashes should work. You'll probably need to modify your server-side check definitions for Windows to send the appropriate command for Windows clients. I'm not too sure what the usual pattern is for having different check definitions for different subscribed clients, possibly having different subscription sets.

**Comment by rmc3** [comment]
Also, I'd recommend testing the scripts manually on the host (log on, run the check command in a shell, make sure it does what you expect) as part of debugging the issue. For normal check plugins, Sensu just executes the command in the check run request, so it's a very easy debugging technique.

**Comment by rmc3** [comment]
Althought, now that I read your message again, all of that might be moot because you say you're getting *some* data from this check :) Still, I do recommend running the check manually and making sure it does what you expect.

**Comment by rmc3** [comment]
Also, what version of Windows are you running this check on?

**Comment by corest** [comment]
@rmc3 
I'm using Windows 2012 R2. I tested all metrics command on the windows host machine. And when i run this script without specifying path to ruby exe - it works even in that case. But i think, that it is because Windows knows about which program used for opening rb files. All tests show proper metrics. Even more - i checked RabbitMq connections - and i see all my machines, connected to rabbitmq. But when OS receives  request for check from Sensu-server - it doesn't know how to open rb file. That is why it hangs. I put full path to ruby executable like you recommended. And it works now. Thank you so much!

**Comment by mattyjones** [comment]
@corest 

We leave the extension intact for the specifically for Windows so that it will be able to detect the file type otherwise it would be long gone ;)
