### ISSUE TITLE
Varnish-metrics hang

### ISSUE THREAD

**Issue by jhmartin** [sensu/sensu-community-plugins#946]
varnish-metrics calls varnishstat which occasionally hangs, preventing the metrics from being gathered until the process is killed (normally by restarting sensu-client).  The hang causes sensu to log:
```json
{"timestamp":"2015-01-07T10:21:38.828224-0500","level":"warn","message":"previous check command execution in progress","check":{"type":"metric","command":"/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/varnish-metrics.rb -n SNIP","standalone":true,"handlers":["relay"],"interval":60,"name":"varnish-metrics","issued":1420644098}}
```

The plugin should apply a timeout to the execution of varnishstat.

http://stackoverflow.com/questions/8292031/ruby-timeouts-and-system-commands looks like it might describe how to implement a timeout.

**Comment by bsnape** [comment]
My team have used this metric for a few months now and while we haven't seen any explicit errors, there does seem to be quite a lag period (1-2 minutes) before results are available in Graphite. It could be for this reason.

I think if work was done in this area we should also change the check to output JSON rather than XML (`-j` flag rather than `-x`): https://github.com/sensu/sensu-community-plugins/blob/master/plugins/varnish/varnish-metrics.rb#L64

This will make the output simpler and faster to parse.

Happy to do this myself (along with investigating the above) once I get chance.
